name: 'Push web notification'
description: 'Push the web notification if there are new posts.'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  msg: # id of output
    description: 'The execution result'
runs:
  using: 'node12'
  main: 'index.js'